Repository pwyq/Fill-Game, pull requests merged in 2023-03, with the labels that each got.

#12 DEV: help menus
  .clang-format
  .vscode/settings.json
  CMakeLists.txt
  fillgame.qrc
  generate_qrc.py
  include/gui/main_window.h
  include/gui/popup_selection.h
  include/gui/popup_window.h
  linux_build.sh
  resource/html/about.html
  resource/html/log.html
  resource/html/rules.html
  resource/icons/fill_game_logo.ico
  resource/icons/fill_game_logo.png
  resource/images/Polyominous.png
  resource/images/Solved_9x9_Fillomino.png
  src/CMakeLists.txt
  src/gui/main_window.cpp
  src/gui/popup_window.cpp
  src/main.cpp
Labels: gui

#13 DEV: separate GUI / solver cmake build
  .gitignore
  CMakeLists.txt
  README.md
  linux_build.sh
  src/CMakeLists.txt
  src/gui_main.cpp
  src/solver/fillgame.cpp
  src/solver_main.cpp
Labels: enhancement

#22 DEV: minimax algo
  .github/workflows/c-cpp.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  include/solver/dfpn.h
  include/solver/minimax.h
  include/solver/node.h
  linux_build.sh
  src/solver/minimax.cpp
  src/solver/node.cpp
  src/solver_main.cpp
  test/README.md
  test/dfpn_test.h
  test/minimax_test.h
  test/test_main.cpp
Labels: algorithm

#31 DEV: negamax with alphabeta and transposition table
  include/solver/dfpn.h
  include/solver/negamax.h
  include/solver/node.h
  src/solver/dfpn.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver_main.cpp
  test/negamax_alphabeta_tt_test.h
  test/test_main.cpp
Labels: algorithm

#33 separate node and nodett
  include/solver/negamax.h
  include/solver/node.h
  src/solver/negamax.cpp
  src/solver/node.cpp
Labels: enhancement

#35 DEV: implement minimax alphabeta transposition table
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver_main.cpp
  test/minimax_alphabeta_tt_test.h
  test/test_main.cpp
Labels: algorithm

#28 ci: update GitHub Actions
  .github/workflows/c-cpp.yml
Labels: enhancement

#38 Issue #25 -- Move Ordering
  src/solver/game.cpp
Labels: enhancement

#41 feat: implement constraint on Windows (probably)
  README.md
  include/solver/constraint.h
  src/solver/constraint.cpp
  src/solver_main.cpp
Labels: enhancement

#37 Develop PNS
  .vscode/launch.json
  .vscode/settings.json
  README.md
  include/solver/helper.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  include/solver/pns.h
  src/solver/game.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver/pns.cpp
  src/solver_main.cpp
  test/pns_test.h
  test/test_main.cpp
Labels: help wanted, algorithm

#44 DEV: optimize class member scope
  include/gui/board_cell.h
  include/solver/constraint.h
  include/solver/dfpn.h
  include/solver/game.h
  include/solver/helper.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  include/solver/pns.h
  include/solver/pns_node.h
  src/gui/main_window.cpp
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver/pns.cpp
  src/solver/pns_node.cpp
  src/solver_main.cpp
Labels: enhancement

#45 feat: implement peak memory usage measure
  .gitignore
  CMakeLists.txt
  README.md
  include/solver/helper.h
  run_experiments.sh
  src/solver/helper.cpp
  test/CMakeLists.txt
  test/experiments.cpp
  test/plot.py
Labels: enhancement, function

#49 DEV: improve UI
  .vscode/launch.json
  CMakeLists.txt
  fillgame.qrc
  include/gui/board_cell.h
  include/gui/info_dock.h
  include/gui/main_window.h
  include/gui/popup_selection.h
  resource/custom_qss/info_dock.qss
  src/gui/board_cell.cpp
  src/gui/info_dock.cpp
  src/gui/main_window.cpp
  src/gui/popup_selection.cpp
  src/gui_main.cpp
Labels: gui

#51 DEV: solver frozen GUI
  .vscode/settings.json
  include/gui/board_cell.h
  include/gui/helper.h
  include/gui/info_dock.h
  include/gui/input_dialog.h
  include/gui/main_window.h
  include/gui/main_window_menu_bar.h
  include/gui/worker.h
  src/gui/board_cell.cpp
  src/gui/helper.cpp
  src/gui/info_dock.cpp
  src/gui/input_dialog.cpp
  src/gui/main_window.cpp
  src/gui/main_window_menu_bar.cpp
  src/gui/worker.cpp
Labels: bug, gui
