Repository pwyq/Fill-Game, pull requests merged in 2023-04, with the labels that each got.

#52 DEV: communicataion between applications
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  CMakeLists.txt
  include/gui/helper.h
  include/gui/info_dock.h
  include/gui/ip_settings.h
  include/gui/main_window.h
  include/gui/main_window_menu_bar.h
  include/gui/new_game_window.h
  include/gui/tcp_client.h
  include/gui/tcp_server.h
  src/CMakeLists.txt
  src/gui/helper.cpp
  src/gui/info_dock.cpp
  src/gui/input_dialog.cpp
  src/gui/ip_settings.cpp
  src/gui/main_window.cpp
  src/gui/main_window_menu_bar.cpp
  src/gui/new_game_window.cpp
  src/gui/tcp_client.cpp
  src/gui/tcp_server.cpp
  src/gui/worker.cpp
Labels: function

#55 tr() QString
  src/gui/info_dock.cpp
  src/gui/main_window.cpp
  src/gui/main_window_menu_bar.cpp
  src/gui/new_game_window.cpp
Labels: gui

#58 feat: update plot.py
  .gitattributes
  run_experiments.sh
  test/plot.py
Labels: enhancement

#60 feat: 2d vs 1d tests
  include/solver/helper.h
  test/CMakeLists.txt
  test/experiments.cpp
  test/other_tests/twoD_vs_oneD.cpp
Labels: enhancement

#56 DEV: optimizations on Game class
  include/solver/game.h
  src/gui/main_window.cpp
  src/solver/game.cpp
  src/solver/node.cpp
  src/solver/pns.cpp
  src/solver_main.cpp
Labels: enhancement

#64 FIX minimax-ab-tt
  src/solver/minimax.cpp
Labels: bug

#62 DEV: central test cases
  include/solver/dfpn.h
  src/solver/dfpn.cpp
  src/solver/game.cpp
  src/solver_main.cpp
  test/algorithm_test_cases.h
  test/dfpn_test.h
  test/minimax_alphabeta_test.h
  test/minimax_alphabeta_tt_test.h
  test/minimax_test.h
  test/negamax_alphabeta_test.h
  test/negamax_alphabeta_tt_test.h
  test/negamax_test.h
  test/other_tests/README.md
  test/other_tests/twoD_vs_oneD.cpp
  test/pns_test.h
  test/test_main.cpp
Labels: enhancement

#68 Agent Playing against each other
  .gitignore
  include/solver/helper.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  include/solver/pns.h
  include/solver/pns_node.h
  linux_build.sh
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/pns.cpp
  src/solver_main.cpp
  test/algorithm_test_cases.h
  test/other_tests/README.md
  test/other_tests/agent_fight.cpp
  test/other_tests/twoD_vs_oneD.cpp
Labels: function

#70 feat: implement MCTS
  README.md
  include/solver/constraint.h
  include/solver/dfpn.h
  include/solver/mcts.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  include/solver/pns.h
  include/solver/pns_node.h
  linux_build.sh
  src/gui/worker.cpp
  src/solver/game.cpp
  src/solver/mcts.cpp
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver/pns.cpp
  src/solver_main.cpp
  test/CMakeLists.txt
  test/README.md
  test/algorithms/algorithm_test_cases.h
  test/algorithms/dfpn_test.h
  test/algorithms/minimax_alphabeta_test.h
  test/algorithms/minimax_alphabeta_tt_test.h
  test/algorithms/minimax_test.h
  test/algorithms/negamax_alphabeta_test.h
  test/algorithms/negamax_alphabeta_tt_test.h
  test/algorithms/negamax_test.h
  test/algorithms/pns_test.h
  test/helper.cpp
  test/helper.h
  test/other_tests/README.md
  test/other_tests/agent_fight.cpp
  test/other_tests/experiments.cpp
  test/other_tests/twoD_vs_oneD.cpp
  test/test_main.cpp
Labels: algorithm

#76 Fixed DFPN best move selection (#74)
  src/solver/dfpn.cpp
  src/solver_main.cpp
Labels: bug

#73 ADD MCTS unit tests; MCTS bugs fix
  include/solver/helper.h
  include/solver/mcts.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/node.h
  src/solver/dfpn.cpp
  src/solver/mcts.cpp
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/node.cpp
  src/solver_main.cpp
  test/README.md
  test/algorithms/algorithm_test_cases.h
  test/algorithms/dfpn_test.h
  test/algorithms/mcts_test.h
  test/algorithms/minimax_alphabeta_test.h
  test/algorithms/minimax_alphabeta_tt_test.h
  test/algorithms/minimax_test.h
  test/algorithms/negamax_alphabeta_test.h
  test/algorithms/negamax_alphabeta_tt_test.h
  test/algorithms/negamax_test.h
  test/algorithms/pns_test.h
  test/other_tests/agent_fight.cpp
  test/test_main.cpp
Labels: bug, function

#77 Fixed MCTS best move selection (#74)
  include/solver/mcts.h
  src/solver/mcts.cpp
  test/algorithms/mcts_test.h
Labels: bug

#80 GUI: enable other agent fight
  include/gui/helper.h
  include/gui/worker.h
  src/gui/main_window.cpp
  src/gui/new_game_window.cpp
  src/gui/worker.cpp
  test/CMakeLists.txt
Labels: gui

#82 Improved MCTS formula to be consistent with AlphaGo
  src/solver/mcts.cpp
Labels: algorithm

#85 Implement node counts for every algorithm and experiments
  include/solver/mcts.h
  include/solver/minimax.h
  include/solver/negamax.h
  include/solver/pns.h
  src/solver/helper.cpp
  src/solver/mcts.cpp
  src/solver/minimax.cpp
  src/solver/negamax.cpp
  src/solver/pns.cpp
  src/solver_main.cpp
Labels: bug, algorithm, experiment
